from __future__ import annotations

from collections.abc import Callable, Iterator
from typing import Any, Literal, overload

class DmlDbError(Exception): ...
class DmlDbInvalidHandleError(DmlDbError): ...
class DmlDbClosedError(DmlDbError): ...
class DmlDbForkedError(DmlDbError): ...
class DmlDbInvalidTxnError(DmlDbError): ...
class DmlDbReadonlyTxnError(DmlDbError): ...
class DmlDbForkedTxnError(DmlDbError): ...
class DmlDbInvalidInputError(ValueError, DmlDbError): ...
class DmlDbInvalidTypeError(ValueError, DmlDbError): ...
class DmlDbInvalidPathError(ValueError, DmlDbError): ...
class DmlDbInvalidRefError(ValueError, DmlDbError): ...
class DmlDbInvalidNamespaceError(ValueError, DmlDbError): ...
class DmlDbKeyNotFoundError(DmlDbError): ...
class DmlDbKeyExistsError(DmlDbError): ...
class DmlDbMsgpackError(DmlDbError): ...
class DmlDbOutOfMemoryError(MemoryError, DmlDbError): ...
class DmlDbMapFullError(DmlDbError): ...
class DmlDbBusyError(DmlDbError): ...
class DmlDbLmdbError(DmlDbError): ...
class DmlDbInternalError(DmlDbError): ...

class Ref:
    to: str

    def __init__(self, to: str) -> None: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: Ref) -> bool: ...
    def __le__(self, other: Ref) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: Ref) -> bool: ...
    def __ge__(self, other: Ref) -> bool: ...
    def __hash__(self) -> int: ...
    def ns(self) -> str: ...
    def id(self) -> str: ...
    def nss(self) -> list[str]: ...

class DmlDb:
    path: str
    namespaces: tuple[str, ...]

    def __init__(
        self,
        path: str,
        namespaces: list[str],
        map_size_headroom: int,
        max_map_size: int,
    ) -> None: ...
    @property
    def get_size(self) -> int: ...
    def resize(self, map_size: int) -> None: ...
    def tx(
        self,
        *,
        readonly: bool = True,
        create_if_missing: bool = False,
    ) -> "DmlDbTxn": ...
    def call_with_resize(self, func: Callable[[DmlDb], None]) -> None: ...

class DmlDbTxn:
    def put(
        self,
        value: object,
        *,
        ns: str | None = None,
        to: Ref | None = None,
        no_overwrite: bool = False,
        raw: bool = False,
    ) -> Ref: ...
    @overload
    def get(self, key: Ref, raw: Literal[False] = False) -> object: ...
    @overload
    def get(self, key: Ref, raw: Literal[True]) -> str: ...
    def get(self, key: Ref, raw: bool = False) -> object | str: ...
    def delete(self, key: Ref) -> None: ...
    def exists(self, key: Ref) -> bool: ...
    def iter(self, ns: str, start_token: Any = None) -> Iterator[tuple[Ref, object]]: ...
    def list_orphans(self, start: list[Ref]) -> list[Ref]: ...
