from __future__ import annotations

from collections.abc import Callable, Iterator
from typing import Any

class DmlDbError(Exception): ...
class DmlDbInvalidTxnError(DmlDbError): ...
class DmlDbReadonlyTxnError(DmlDbError): ...
class DmlDbForkedTxnError(DmlDbError): ...
class DmlDbInvalidInputError(ValueError, DmlDbError): ...
class DmlDbInvalidTypeError(ValueError, DmlDbError): ...
class DmlDbInvalidPathError(ValueError, DmlDbError): ...
class DmlDbInvalidRefError(ValueError, DmlDbError): ...
class DmlDbInvalidNamespaceError(ValueError, DmlDbError): ...
class DmlDbKeyNotFoundError(DmlDbError): ...
class DmlDbKeyExistsError(DmlDbError): ...
class DmlDbMsgpackError(DmlDbError): ...
class DmlDbOutOfMemoryError(MemoryError, DmlDbError): ...
class DmlDbMapFullError(DmlDbError): ...
class DmlDbBusyError(DmlDbError): ...
class DmlDbLmdbError(DmlDbError): ...
class DmlDbInternalError(DmlDbError): ...
class DmlDbRegistryFullError(DmlDbError): ...

class Ref:
    to: str

    def __init__(self, to: str) -> None: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: Ref) -> bool: ...
    def __le__(self, other: Ref) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: Ref) -> bool: ...
    def __ge__(self, other: Ref) -> bool: ...
    def __hash__(self) -> int: ...
    def ns(self) -> str: ...
    def id(self) -> str: ...
    def nss(self) -> list[str]: ...

class DmlDb:
    path: str
    namespaces: tuple[str, ...]

    def __init__(
        self,
        path: str,
        namespaces: list[str],
        map_size_headroom: int,
        max_map_size: int,
    ) -> None: ...
    def resize(self, create_if_missing: bool = False) -> None: ...
    def tx(
        self,
        *,
        map_size: int | None = None,
        readonly: bool = True,
        create_if_missing: bool = False,
    ) -> "DmlDbTxn": ...
    def write_with_growth(self, fn: Callable[[DmlDbTxn], Any], create_if_missing: bool = False) -> Any: ...

class DmlDbTxn:
    def put(
        self,
        value: object,
        *,
        ns: str | None = None,
        to: Ref | None = None,
        no_overwrite: bool = False,
    ) -> Ref: ...
    def get(self, key: Ref) -> object: ...
    def delete(self, key: Ref) -> None: ...
    def exists(self, key: Ref) -> bool: ...
    def iter(self, ns: str, start_token: Any = None) -> Iterator[tuple[Ref, object]]: ...
    def list_orphans(self, start: list[Ref], missing_commit_refs: list[Ref] | None = None) -> list[Ref]: ...
