[envs.default]
python="3.10"

[envs.test]
dependencies = [
  "pytest",
  "pytest-cov",
  "pandas==2.0.1",
]

[envs.test.scripts]
test = 'pytest -vsx --log-cli-level=INFO --log-disable=botocore.credentials'

[build.targets.wheel]
packages = ["src/daggerml"]
