[project]
name = "daggerml"
authors = [
  { name="Aaron Niskin", email="aaron@daggerml.com" },
  { name="Micha Niskin", email="micha@daggerml.com" },
]
description = "DaggerML"
readme = "README.md"
license = "MIT"
requires-python = ">=3.6"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "dataclasses; python_version < '3.7'"
]
dynamic = ["version"]

[project.optional-dependencies]
aws = [
  "boto3>=1.0"
]

[project.urls]
Homepage = "https://daggerml.com"
Documentation = "https://daggerml.com/docs"
Issues = "https://github.com/daggerml/python-lib/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.version]
path = "daggerml/__about__.py"


[tool.hatch.envs.default]
python = "38"
dependencies = []

[tool.hatch.envs.quick-test]
python = "37"
dependencies = [
  "pytest",
  "pytest-cov",
]

[tool.hatch.envs.quick-test.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=daggerml --cov=tests"
no-cov = "cov --no-cov"


[tool.hatch.envs.test]
dependencies = [
  "pytest",
  "pytest-cov"
]

[tool.hatch.envs.test.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=daggerml --cov=tests"
no-cov = "cov --no-cov"

[[tool.hatch.envs.test.matrix]]
python = ["36", "37", "38", "39", "310"]

[tool.hatch.envs.docs]
python = "38"
dependencies = [
  "Sphinx>=5.1.1",
  "sphinx-rtd-theme>=1.0.0",
  "nbsphinx>=0.8.9",
  "jupytext>=1.14.1",
  "matplotlib>=3.5.3",
  "numpy>=1.23.2",
  "jupyter>=1.0.0",
  "pandas>=1.4.3",
  "boto3>=1.0",
  "pyarrow>=9.0.0",
  "s3fs>=2022.7.1",
]

[tool.hatch.envs.docs.scripts]
build = '(cd docs && make html)'
serve = '(cd docs/_build/html && python -m http.server 8080)'


[tool.coverage.run]
branch = true
parallel = true
omit = [
  "daggerml/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
