[tool.poetry]
name = "daggerml"
version = "0.1.0"
description = ""
authors = ["Aaron Niskin <amniskin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = ">=1.0"

[tool.poetry.dev-dependencies]
Sphinx = "^5.1.1"
sphinx-rtd-theme = "^1.0.0"
nbsphinx = "^0.8.9"
jupytext = "^1.14.1"
matplotlib = "^3.5.3"
numpy = "^1.23.2"
jupyter = "^1.0.0"
pandas = "^1.4.3"
pyarrow = "^9.0.0"
s3fs = "^2022.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
