[tool.poetry]
name = "dml"
version = "0.1.0"
description = ""
authors = ["Aaron Niskin <amniskin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
boto3 = "^1.24.53"

[tool.poetry.dev-dependencies]
Sphinx = "^5.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
