line-length = 120

# Enable flake8-bugbear (`B`) rules. PGH004 catches blanket noqa tags
select = ["E", "F", "B", "I", "PGH004"]

ignore = []

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

[per-file-ignores]
"__init__.py" = ["F401", "E401", "E402", "I001"]

[isort]
known-first-party = ["daggerml"]
