from __future__ import annotations

from collections.abc import Iterator
from contextlib import AbstractContextManager
from typing import Any, Literal, Self, overload

class DmlDbError(Exception): ...
class DmlDbInvalidHandleError(DmlDbError): ...
class DmlDbClosedError(DmlDbError): ...
class DmlDbForkedError(DmlDbError): ...
class DmlDbInvalidTxnError(DmlDbError): ...
class DmlDbReadonlyTxnError(DmlDbError): ...
class DmlDbForkedTxnError(DmlDbError): ...
class DmlDbInvalidInputError(ValueError, DmlDbError): ...
class DmlDbInvalidTypeError(ValueError, DmlDbError): ...
class DmlDbInvalidPathError(ValueError, DmlDbError): ...
class DmlDbInvalidRefError(ValueError, DmlDbError): ...
class DmlDbInvalidNamespaceError(ValueError, DmlDbError): ...
class DmlDbKeyNotFoundError(DmlDbError): ...
class DmlDbKeyExistsError(DmlDbError): ...
class DmlDbMsgpackError(DmlDbError): ...
class DmlDbOutOfMemoryError(MemoryError, DmlDbError): ...
class DmlDbMapFullError(DmlDbError): ...
class DmlDbBusyError(DmlDbError): ...
class DmlDbLmdbError(DmlDbError): ...
class DmlDbInternalError(DmlDbError): ...
class DmlDbEnvReopenedError(DmlDbError): ...

class Ref:
    to: str

    def __init__(self, to: str) -> None: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: Ref) -> bool: ...
    def __le__(self, other: Ref) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: Ref) -> bool: ...
    def __ge__(self, other: Ref) -> bool: ...
    def __hash__(self) -> int: ...
    def ns(self) -> str: ...
    def id(self) -> str: ...
    def nss(self) -> list[str]: ...

class DmlDbEnv:
    path: str
    namespaces: tuple[str, ...]

    @property
    def closed(self) -> bool: ...
    @classmethod
    def _open(
        cls, path: str, namespaces: list[str], create_if_missing: bool = False, map_size: int | None = None
    ) -> Self: ...
    @classmethod
    def create(cls, path: str, namespaces: list[str], map_size: int | None = None) -> Self: ...
    @classmethod
    def open(cls, path: str, namespaces: list[str], map_size: int | None = None) -> Self: ...
    def get_size(self) -> int: ...
    def resize(self, new_size: int) -> None: ...
    def tx(self, readonly: bool = True) -> AbstractContextManager[DmlDbEnvTxn]: ...
    def close(self) -> None: ...

class DmlDbEnvTxn:
    @property
    def closed(self) -> bool: ...
    def commit(self) -> None: ...
    def abort(self) -> None: ...
    def put(
        self,
        value: object,
        *,
        ns: str | None = None,
        to: Ref | None = None,
        no_overwrite: bool = False,
        raw: bool = False,
    ) -> Ref: ...
    @overload
    def get(self, key: Ref, raw: Literal[False] = False) -> dict: ...
    @overload
    def get(self, key: Ref, raw: Literal[True]) -> str: ...
    def get(self, key: Ref, raw: bool = False) -> dict | str: ...
    def delete(self, key: Ref) -> None: ...
    def exists(self, key: Ref) -> bool: ...
    def iter(self, ns: str, start_token: Any = None) -> Iterator[tuple[Ref, object]]: ...
    def list_orphans(self, start: list[Ref]) -> list[Ref]: ...
