project:
  type: default
  output-dir: _build
  render:
    - "**/*.qmd"

execute:
  eval: true
  error: false
  cache: false
  freeze: false

format:
  html:
    toc: false
    embed-resources: false
